/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14.4/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.10.0"
}

rootProject.name = "libs"
include("shared")
include("celery")
include("celery-api")

include("celery-platform:celery-mongodb")
include("celery-platform:celery-redis")
include("celery-platform:celery-redis-cache")
include("celery-platform:celery-redis-cluster")
include("celery-platform:celery-redis-cache-cluster")
include("celery-platform:celery-influxdb")
include("celery-platform:celery-nats")
include("celery-platform:celery-nats-cluster")
include("celery-platform:celery-s3")
include("testing")
